
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/tmp/pip-build-env-8psjdkw_/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.0-1073-azure - x86_64
...
